### ISSUE TITLE
Chroma not working for razer huntsman mini

### ISSUE THREAD

**Issue by Filtar2000** [bonepl/ChromaLeague#118]
When i run chromaleague the cmd opens. When i get in the game no chroma effect starts

**Comment by bonepl** [comment]
Do you get any logs in cmd? Can you share them?
Can you share what do you have when you visit [http://localhost:54235/razer/chromasdk](http://localhost:54235/razer/chromasdk)

**Comment by Filtar2000** [comment]
I dont get any logs, there's no effect on the keyboard. Only loading works, but when im in game no effect works

**Comment by Filtar2000** [comment]
{"core":"3.23.02","device":"3.23.02","version":"3.23.03"}

**Comment by Filtar2000** [comment]
What happened before for example was that the loading animation on the keyboard worked. Then when the game started only the numbers row of the keyboard was illuminated and the other buttons weren't

**Comment by Filtar2000** [comment]
Maybe the chroma effects aren't supported by razer huntsman mini

**Comment by bonepl** [comment]
When you start a game, only your hp and mana bar are visible, so not much.
Try killing another champion or dragon and see if there are additional animations.

ChromaLeague reacts to ingame events.

**Comment by Filtar2000** [comment]
shouldn't also the other buttons be illuminated?
I only had the numbers in blue, the rest was with no color

**Comment by Filtar2000** [comment]
i will try

**Comment by bonepl** [comment]
Ah I see where the issue is. Hunstman mini has a very small set of keys. It doesn't have F1 - F12 keys which show health bar and it doesn't have numeric keyboard which is used for showing gold, it doesn't have functional keys area which is for showing enemy objectives but rest of the integrations like mana, killed dragons counter, ally objectives, baron buff, elder buff, backlight, and win/lose animations will still work.

That's why u only saw blue bar at numbers which is for mana/energy.

Unfortunately this keyboard has too small set of keys to fully show the integration :(
